config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "courses#index"
  resources :courses, only: %i[index show new create]
  resources :user_threads, only: %i[show create] do
    resources :messages, only: %i[create], module: :user_threads
    resources :notebooks, only: %i[create], module: :user_threads
  end
  resources :topics, only: %i[show] do
    member do
      post :start
    end
  end
  resources :notebooks, only: %i[index show]
end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id                 :integer          not null, primary key
#  user_thread_id     :integer          not null
#  content            :string
#  sender_type        :integer
#  message_identifier :string
#  status             :integer
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#
# Indexes
#
#  index_messages_on_user_thread_id  (user_thread_id)
#

class Message < ApplicationRecord
  include ActionView::RecordIdentifier
  belongs_to :user_thread
  enum :sender_type, { user: 1, assistant: 2 }, prefix: true, validate: true
  enum :status, { before_processing: 0, processing: 1, completed: 2, failed: 3, expired: 4 }, prefix: true, validate: true

  def broadcast_chunk_received
    broadcast_replace_to(
      dom_id(user_thread),
      partial: "user_threads/messages/message",
      locals: { message: self, scroll_to: true },
      target: "#{dom_id(self)}"
    )

    return unless user_thread.status == "completed"

    broadcast_replace_to(
      dom_id(user_thread),
      partial: "user_threads/messages/form",
      locals: { form_disabled: false, user_thread: user_thread, message: nil },
      target: "form"
    )

    broadcast_replace_to(
      dom_id(user_thread),
      partial: "user_threads/topic_list",
      locals: {
        topics: user_thread.topic.chapter.topics.order(created_at: :asc).to_a, # TODO: positionでソートする
        current_topic_id: user_thread.topic_id,
        user: user_thread.user
      },
      target: "topic_list"
    )
  end
end

app/models/user_thread.rb
# == Schema Information
#
# Table name: user_threads
#
#  id                    :integer          not null, primary key
#  user_id               :integer          not null
#  topic_id              :integer          not null
#  thread_identifier     :string
#  latest_run_identifier :string
#  status                :integer
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#  notebook_status       :integer
#
# Indexes
#
#  index_user_threads_on_topic_id  (topic_id)
#  index_user_threads_on_user_id   (user_id)
#

class UserThread < ApplicationRecord
  include ActionView::RecordIdentifier
  belongs_to :user
  belongs_to :topic
  has_one :user_thread_progress, dependent: :destroy
  has_many :messages, dependent: :destroy
  enum :status, { unprocessed: 0, queued: 1, in_progress: 2, cancelling: 3, completed: 4, requires_action: 5, cancelled: 6, failed: 7, expired: 8 }, prefix: true, validate: true
  enum :notebook_status, { in_progress: 0, completed: 1 }, prefix: true, validate: true, default: :completed


  def broadcast_notebook_created
    broadcast_replace_later_to(
      dom_id(self),
      partial: "user_threads/notebook_list",
      locals: {
        notebooks: Notebook.where(topic:, user:).order(created_at: :asc).to_a,
        user_thread: self
      },
      target: "notebook_list"
    )
  end

  def create_notebooks
    message_histories = messages.order(created_at: :asc)
    message_history_array = message_histories.map do |message|
      { role: message.sender_type, content: message.content }
    end
    # message_history_array.pop
    message_history_array << { role: "user", content: "「#{topic.chapter.course.title}」「#{topic.chapter.title}」「#{topic.title}」というコンテキストにおいて、上記のやりとりからユーザーの理解度があいまいな点を整理して列挙してください。" }
    client = OpenAI::Client.new(access_token: Rails.application.credentials.dig(:open_ai, :access_token))
    response = client.chat(
      parameters: {
        model: "gpt-4o-mini", # Required.
        messages: message_history_array,
        temperature: 1.0,
        tools: [
          {
            type: "function",
            function: {
              name: "generate_learning_note",
              description: "Generate a learning note based on the user's weak areas.",
              parameters: {
                type: "object",
                properties: {
                  learning_notes: {
                    type: "array",
                    items: {
                      type: "object",
                      properties: {
                        topic: { type: "string" },
                        model_answer: { type: "string" }
                      },
                      required: ["topic", "model_answer"]
                    }
                  }
                },
                required: ["learning_notes"]
              }
            }
          }
        ],
        # Optional, defaults to "auto"
        # Can also put "none" or specific functions, see docs
        tool_choice: "required"
      }
    )
    message = response.dig("choices", 0, "message")

    if message["role"] == "assistant" && message["tool_calls"]
      message["tool_calls"].each do |tool_call|
        tool_call_id = tool_call.dig("id")
        function_name = tool_call.dig("function", "name")
        function_args = JSON.parse(
          tool_call.dig("function", "arguments"),
          { symbolize_names: true },
          )
        function_response =
          case function_name
          when "generate_learning_note"
            generate_learning_note(**function_args)  # => "The weather is nice 🌞"
          else
            # decide how to handle
          end
      end
    end
  end

  private

  def generate_learning_note(arguments)
    learning_notes = arguments[:learning_notes]
    learning_notes.each do |learning_note|
      title = learning_note[:topic]
      model_answer = learning_note[:model_answer]
      Notebook.find_or_create_by(title:, user_id:, topic_id:) do |notebook|
        notebook.content = model_answer
      end
    end
  end
end

app/controllers/user_threads/messages_controller.rb
class UserThreads::MessagesController < ApplicationController
  def create
    @user_thread = UserThread.find_by!(user_id: current_user.id, id: params[:user_thread_id])

    @user_message = Message.new(content: params[:message][:content], sender_type: :user, user_thread_id: @user_thread.id, status: :completed)

    if @user_message.save
      @assistant_message = Message.create!(content: "", sender_type: :assistant, user_thread_id: @user_thread.id, status: :before_processing)
      PostMessageToAiJob.perform_later(user_message_id: @user_message.id, assistant_message_id: @assistant_message.id)
    else
      @messages = @user_thread.messages.order(created_at: :asc).offset(1)
      @message = @user_message
      render "threads/show", status: :unprocessable_content
    end
  end
end

app/controllers/user_threads/notebooks_controller.rb
class UserThreads::NotebooksController < ApplicationController
  def create
    user_thread = UserThread.find(params[:user_thread_id])
    user_thread.update(notebook_status: :in_progress)
    CreateNotebooksJob.perform_later(user_thread_id: user_thread.id)
    redirect_to user_thread
  end
end

app/controllers/user_threads_controller.rb
class UserThreadsController < ApplicationController
  def show
    @user_thread = current_user.user_threads.find(params[:id])

    @messages = @user_thread.messages.order(created_at: :asc).offset(1)
    @topics = @user_thread.topic.chapter.topics.order(position: :asc)
  end
end

app/views/user_threads/messages/_form.html.erb
<%= turbo_frame_tag "form", class: 'absolute bottom-4 left-6 right-4' do %>
  <%# ブロードキャストではidがnilのオブジェクトをシリアライズできないので仕方なくここでmessageがなかったときはMessage.newをするようにしてる %>
  <% message ||= Message.new %>
  <% unless user_thread.user_thread_progress.status_completed? %>
    <div class="w-full pt-2 md:pt-0 md:border-transparent md:w-[calc(100%-.5rem)]">
      <%= form_with model: message, url: user_thread_messages_path(user_thread), data: { controller: 'enter-submit' } do |f| %>
        <div class="relative">
          <%= f.text_area :content, class: 'rounded-2xl m-0 w-full resize-none py-[10px] pr-10 focus:ring-0 focus-visible:ring-0 md:py-3.5 md:pr-12 placeholder-black/50 pl-4 focus:border-token-border-xheavy focus:shadow-[0_2px_6px_rgba(0,0,0,.05)] border border-token-border-heavy', required: true, disabled: form_disabled, data: { controller: 'textarea-autosize', action: 'keydown->enter-submit#checkKeyPress' } %>
          <%= button_tag type: :submit,
                         class: 'absolute md:bottom-3 md:right-3 right-2 disabled:bg-black disabled:opacity-10 disabled:text-gray-400 enabled:bg-black text-white p-0.5 border border-black rounded-lg bottom-1.5 transition-colors',
                         disabled: form_disabled, data: { 'enter-submit-target': 'submit' } do %>
            <span class="" data-state="closed"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" class="text-white"><path d="M7 11L12 6L17 11M12 18V7" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path></svg></span>
          <% end %>
        </div>

        <% if message.errors.any? %>
          <div id="error_explanation">
            <ul>
              <% message.errors.full_messages.each do |message| %>
                <li class="text-xs text-red-600"><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
  <% if user_thread.user_thread_progress.status_completed? %>
    <div class="w-full pt-2 md:pt-0 md:border-transparent md:w-[calc(100%-.5rem)]">
      <div class="rounded-2xl m-0 w-full resize-none py-[10px] pr-10 md:py-3.5 md:pr-12 placeholder-black/50 pl-4 focus:border-token-border-xheavy focus:shadow-[0_2px_6px_rgba(0,0,0,.05)] border border-token-border-heavy bg-gray-100 text-gray-400 text-center">
        <div class="flex items-center justify-around">
          このスレッドは終了しました
          <%= render 'user_threads/model_answer', topic: user_thread.topic %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/user_threads/messages/_message.html.erb
<div id="<%= dom_id(message) %>">
  <% if message.status_before_processing? %>
    <div class="w-full text-token-text-primary">
      <div class="px-4 py-2 justify-center text-sm md:gap-6 m-auto">
        <div class="flex flex-1 text-sm mx-auto gap-3">
          <div class="flex-shrink-0 flex flex-col relative items-end">
            <div>
              <div class="pt-0.5">
                <div class="gizmo-shadow-stroke flex h-6 w-6 items-center justify-center overflow-hidden rounded-full">
                  <div class="relative flex">
                    <div class="bg-black p-1">
                      <%= image_tag 'ai.png' %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="relative flex w-full flex-col lg:w-[calc(100%-115px)]">
            <div class="font-semibold select-none">AI</div>
            <div class="flex-col gap-1 md:gap-3">
              <div class="flex flex-grow flex-col max-w-full">
                <div class="min-h-[20px] text-message break-words [.text-message+&amp;]:mt-5 overflow-x-auto">
                  <div class="flex justify-center my-6 items-center gap-2">
                    <span>生成中...</span>
                    <svg class="animate-spin -ml-1 mr-3 h-5 w-5 text-indigo-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                      <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                      <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                    </svg>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% elsif message.status_failed? %>
    <div class="w-full text-token-text-primary">
      <div class="px-4 py-2 justify-center text-sm md:gap-6 m-auto">
        <div class="flex flex-1 text-sm mx-auto gap-3">
          <div class="flex-shrink-0 flex flex-col relative items-end">
            <div>
              <div class="pt-0.5">
                <div class="gizmo-shadow-stroke flex h-6 w-6 items-center justify-center overflow-hidden rounded-full">
                  <div class="relative flex">
                    <div class="bg-black p-1">
                      <%= image_tag 'ai.png' %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="relative flex w-full flex-col lg:w-[calc(100%-115px)]">
            <div class="font-semibold select-none">AI</div>
            <div class="flex-col gap-1 md:gap-3">
              <div class="flex flex-grow flex-col max-w-full">
                <div class="min-h-[20px] text-message break-words [.text-message+&amp;]:mt-5 overflow-x-auto">
                  <div class="flex justify-center my-6 items-center gap-2">
                    <div class="text-center">
                      <div class="text-red-600 mb-2">生成に失敗しました</div>
                      <%#= form_with url: retry_thread_message_path(message.user_thread, message) do |f| %>
                        <%#= f.submit '再生成', class: 'cursor-pointer inline-flex items-center justify-center rounded-md text-xs lg:text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-primary text-primary-foreground hover:bg-primary/90 px-4 py-2' %>
                      <%# end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% else %>
    <div class="w-full text-token-text-primary">
      <div class="px-4 py-2 justify-center text-sm md:gap-6 m-auto">
        <div class="flex flex-1 text-sm mx-auto gap-3">
          <div class="flex-shrink-0 flex flex-col relative items-end">
            <div>
              <div class="pt-0.5">
                <div class="gizmo-shadow-stroke flex h-6 w-6 items-center justify-center overflow-hidden rounded-full">
                  <div class="relative flex">
                    <% if message.sender_type_assistant? %>
                      <div class="bg-black p-1">
                        <%= image_tag 'ai.png' %>
                      </div>
                    <% else %>
                      <%#= image_tag message.user_thread.user.avatar, loading: "lazy", size: '24x24', class: 'rounded-sm' %>
                      <svg class="" width="24" height="24" viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg"><title/><g id="about"><path d="M16,16A7,7,0,1,0,9,9,7,7,0,0,0,16,16ZM16,4a5,5,0,1,1-5,5A5,5,0,0,1,16,4Z"/><path d="M17,18H15A11,11,0,0,0,4,29a1,1,0,0,0,1,1H27a1,1,0,0,0,1-1A11,11,0,0,0,17,18ZM6.06,28A9,9,0,0,1,15,20h2a9,9,0,0,1,8.94,8Z"/></g></svg>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="relative flex w-full flex-col lg:w-[calc(100%-115px)]">
            <div class="font-semibold select-none"><%= message.sender_type_assistant? ? 'AI' : 'あなた' %></div>
            <div class="flex-col gap-1 md:gap-3">
              <div class="flex flex-grow flex-col max-w-full">
                <div class="min-h-[20px] text-message break-words [.text-message+&amp;]:mt-5 overflow-x-auto">
                  <div class="markdown-body">
                    <%#= simple_format(message.content) %>
                    <%= markdown message.content || '' %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/user_threads/messages/create.turbo_stream.erb
<%= turbo_stream.append 'messages' do %>
  <%= render "user_threads/messages/message", message: @user_message, scroll_to: true %>
  <%= render "user_threads/messages/message", message: @assistant_message, scroll_to: true %>
<% end %>

<%= turbo_stream.replace "form" do %>
  <%= render "user_threads/messages/form", form_disabled: true, message: Message.new, user_thread: @user_thread %>
<% end %>