config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "courses#index"
  resources :courses, only: %i[index show new create]
  resources :user_threads, only: %i[show create] do
    resources :messages, only: %i[create], module: :user_threads
    resources :notebooks, only: %i[create], module: :user_threads
  end
  resources :topics, only: %i[show] do
    member do
      post :start
    end
  end
  resources :notebooks, only: %i[index show]
end

app/models/user_thread.rb
# == Schema Information
#
# Table name: user_threads
#
#  id                    :integer          not null, primary key
#  user_id               :integer          not null
#  topic_id              :integer          not null
#  thread_identifier     :string
#  latest_run_identifier :string
#  status                :integer
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#  notebook_status       :integer
#
# Indexes
#
#  index_user_threads_on_topic_id  (topic_id)
#  index_user_threads_on_user_id   (user_id)
#

class UserThread < ApplicationRecord
  include ActionView::RecordIdentifier
  belongs_to :user
  belongs_to :topic
  has_one :user_thread_progress, dependent: :destroy
  has_many :messages, dependent: :destroy
  enum :status, { unprocessed: 0, queued: 1, in_progress: 2, cancelling: 3, completed: 4, requires_action: 5, cancelled: 6, failed: 7, expired: 8 }, prefix: true, validate: true
  enum :notebook_status, { in_progress: 0, completed: 1 }, prefix: true, validate: true, default: :completed


  def broadcast_notebook_created
    broadcast_replace_later_to(
      dom_id(self),
      partial: "user_threads/notebook_list",
      locals: {
        notebooks: Notebook.where(topic:, user:).order(created_at: :asc).to_a,
        user_thread: self
      },
      target: "notebook_list"
    )
  end

  def create_notebooks
    message_histories = messages.order(created_at: :asc)
    message_history_array = message_histories.map do |message|
      { role: message.sender_type, content: message.content }
    end
    # message_history_array.pop
    message_history_array << { role: "user", content: "「#{topic.chapter.course.title}」「#{topic.chapter.title}」「#{topic.title}」というコンテキストにおいて、上記のやりとりからユーザーの理解度があいまいな点を整理して列挙してください。" }
    client = OpenAI::Client.new(access_token: Rails.application.credentials.dig(:open_ai, :access_token))
    response = client.chat(
      parameters: {
        model: "gpt-4o-mini", # Required.
        messages: message_history_array,
        temperature: 1.0,
        tools: [
          {
            type: "function",
            function: {
              name: "generate_learning_note",
              description: "Generate a learning note based on the user's weak areas.",
              parameters: {
                type: "object",
                properties: {
                  learning_notes: {
                    type: "array",
                    items: {
                      type: "object",
                      properties: {
                        topic: { type: "string" },
                        model_answer: { type: "string" }
                      },
                      required: ["topic", "model_answer"]
                    }
                  }
                },
                required: ["learning_notes"]
              }
            }
          }
        ],
        # Optional, defaults to "auto"
        # Can also put "none" or specific functions, see docs
        tool_choice: "required"
      }
    )
    message = response.dig("choices", 0, "message")

    if message["role"] == "assistant" && message["tool_calls"]
      message["tool_calls"].each do |tool_call|
        tool_call_id = tool_call.dig("id")
        function_name = tool_call.dig("function", "name")
        function_args = JSON.parse(
          tool_call.dig("function", "arguments"),
          { symbolize_names: true },
          )
        function_response =
          case function_name
          when "generate_learning_note"
            generate_learning_note(**function_args)  # => "The weather is nice 🌞"
          else
            # decide how to handle
          end
      end
    end
  end

  private

  def generate_learning_note(arguments)
    learning_notes = arguments[:learning_notes]
    learning_notes.each do |learning_note|
      title = learning_note[:topic]
      model_answer = learning_note[:model_answer]
      Notebook.find_or_create_by(title:, user_id:, topic_id:) do |notebook|
        notebook.content = model_answer
      end
    end
  end
end

app/controllers/user_threads/messages_controller.rb
class UserThreads::MessagesController < ApplicationController
  def create
    @user_thread = UserThread.find_by!(user_id: current_user.id, id: params[:user_thread_id])

    @user_message = Message.new(content: params[:message][:content], sender_type: :user, user_thread_id: @user_thread.id, status: :completed)

    if @user_message.save
      @assistant_message = Message.create!(content: "", sender_type: :assistant, user_thread_id: @user_thread.id, status: :before_processing)
      PostMessageToAiJob.perform_later(user_message_id: @user_message.id, assistant_message_id: @assistant_message.id)
    else
      @messages = @user_thread.messages.order(created_at: :asc).offset(1)
      @message = @user_message
      render "threads/show", status: :unprocessable_content
    end
  end
end

app/controllers/user_threads/notebooks_controller.rb
class UserThreads::NotebooksController < ApplicationController
  def create
    user_thread = UserThread.find(params[:user_thread_id])
    user_thread.update(notebook_status: :in_progress)
    CreateNotebooksJob.perform_later(user_thread_id: user_thread.id)
    redirect_to user_thread
  end
end

app/controllers/user_threads_controller.rb
class UserThreadsController < ApplicationController
  def show
    @user_thread = current_user.user_threads.find(params[:id])

    @messages = @user_thread.messages.order(created_at: :asc).offset(1)
    @topics = @user_thread.topic.chapter.topics.order(position: :asc)
  end
end

app/views/user_threads/_model_answer.html.erb
<!-- Modal toggle -->
<button data-modal-target="static-modal" data-modal-toggle="static-modal" class="block text-white bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5" type="button">
  模範解答を見る
</button>

<!-- Main modal -->
<div id="static-modal" data-modal-backdrop="static" tabindex="-1" aria-hidden="true" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
  <div class="relative p-4 w-full max-w-2xl max-h-full">
    <!-- Modal content -->
    <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
      <!-- Modal header -->
      <div class="flex items-center justify-between p-4 md:p-5 border-b rounded-t dark:border-gray-600">
        <h3 class="text-xl font-semibold text-gray-900 dark:text-white">
          模範回答
        </h3>
        <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-hide="static-modal">
          <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
          </svg>
          <span class="sr-only">Close modal</span>
        </button>
      </div>
      <!-- Modal body -->
      <div class="p-4 md:p-5 space-y-4">
        <p class="font-bold text-black">
          <%= topic.question %>
        </p>
        <div class="markdown-body text-left">
          <%= markdown topic.model_answer %>
        </div>
      </div>
<!--      <div class="flex items-center p-4 md:p-5 border-t border-gray-200 rounded-b dark:border-gray-600">-->
<!--        <button data-modal-hide="static-modal" type="button" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">I accept</button>-->
<!--        <button data-modal-hide="static-modal" type="button" class="py-2.5 px-5 ms-3 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-100 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700">Decline</button>-->
<!--      </div>-->
    </div>
  </div>
</div>

app/views/user_threads/_notebook_list.html.erb
<div id="notebook_list" class="mt-8 p-4 bg-white border border-gray-200 rounded-lg shadow-sm">
  <h2 class="p-2 font-bold text-lg flex items-center gap-2">
    <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
      <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10.779 17.779 4.36 19.918 6.5 13.5m4.279 4.279 8.364-8.643a3.027 3.027 0 0 0-2.14-5.165 3.03 3.03 0 0 0-2.14.886L6.5 13.5m4.279 4.279L6.499 13.5m2.14 2.14 6.213-6.504M12.75 7.04 17 11.28"/>
    </svg>
    弱点ノート
  </h2>
  <hr class="my-2">
  <%= render 'shared/loading_or_content', loading: user_thread.notebook_status_in_progress? do %>
    <% if notebooks.present? %>
      <ol class="space-y-4 w-full">
        <% notebooks.each do |notebook| %>
          <li class="flex items-center space-x-1">
            <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 9a3 3 0 0 1 3-3m-2 15h4m0-3c0-4.1 4-4.9 4-9A6 6 0 1 0 6 9c0 4 4 5 4 9h4Z"/>
            </svg>
            <span>
            <%= link_to notebook.title, notebook_path(notebook), data: { turbo_frame: :modal }, class: 'block p-2 text-blue-600 hover:underline'%>
          </span>
          </li>
        <% end %>
      </ol>
    <% else %>
      <div class="">
        <%= button_to 'AIに弱点をまとめてもらう',
                      user_thread_notebooks_path(user_thread), class: 'text-white bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5' %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/user_threads/_topic.html.erb
<li>
  <% user_topic_progress = UserTopicProgress.find_by(user_id: user.id, topic:) %>
  <% if user_topic_progress.blank? %>
    <%= link_to start_topic_path(topic), data: { turbo_method: :post } do  %>
      <div class="w-full p-4 text-gray-900 bg-white border rounded-lg <%= current_topic_id == topic.id ? 'border border-[3px]' : ''  %>" role="alert">
        <div class="flex items-center justify-between">
          <h3 class="font-medium"><%= topic_counter + 1 %>. <%= topic.title %></h3>
        </div>
      </div>
    <% end %>
  <% elsif user_topic_progress.status_in_progress? %>
    <%= link_to start_topic_path(topic), data: { turbo_method: :post }  do  %>
      <div class="w-full p-4 text-blue-700 bg-blue-100 border border-blue-300 rounded-lg dark:bg-gray-800 dark:border-blue-800 dark:text-blue-400 <%= current_topic_id == topic.id ? 'border border-[3px]' : ''  %>" role="alert">
        <div class="flex items-center justify-between">
          <h3 class="font-medium"><%= topic_counter + 1 %>. <%= topic.title %></h3>
          <svg class="rtl:rotate-180 w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"></path>
          </svg>
        </div>
      </div>
    <% end %>
  <% elsif user_topic_progress.status_completed? %>
    <%= link_to start_topic_path(topic), data: { turbo_method: :post }  do  %>
      <div class="w-full p-4 text-green-700 border border-green-300 rounded-lg bg-green-50 dark:bg-gray-800 dark:border-green-800 dark:text-green-400 <%= current_topic_id == topic.id ? 'border border-[3px]' : ''  %>" role="alert">
        <div class="flex items-center justify-between">
          <h3 class="font-medium"><%= topic_counter + 1 %>. <%= topic.title %></h3>
          <svg class="w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 16 12">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5.917 5.724 10.5 15 1.5"/>
          </svg>
        </div>
      </div>
    <% end %>
  <% end %>
</li>

app/views/user_threads/_topic_list.html.erb
<div id="topic_list" class="sticky top-0 p-4 bg-white border border-gray-200 rounded-lg shadow-sm">
  <h2 class="p-2 font-bold text-lg flex items-center gap-2">
    <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
      <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6.03v13m0-13c-2.819-.831-4.715-1.076-8.029-1.023A.99.99 0 0 0 3 6v11c0 .563.466 1.014 1.03 1.007 3.122-.043 5.018.212 7.97 1.023m0-13c2.819-.831 4.715-1.076 8.029-1.023A.99.99 0 0 1 21 6v11c0 .563-.466 1.014-1.03 1.007-3.122-.043-5.018.212-7.97 1.023"/>
    </svg>
    トピック
  </h2>
  <hr class="my-2">
  <ol class="space-y-4 w-full">
    <%= render partial: 'user_threads/topic', collection: topics, locals: { current_topic_id:, user: } %>
  </ol>
</div>

app/views/user_threads/show.html.erb
<%= turbo_stream_from "#{dom_id(@user_thread)}" %>
<% breadcrumb :user_thread, @user_thread %>
<main>
  <div class="px-4 pt-6">
    <%= render 'shared/breadcrumbs' %>
    <div class="flex lg:flex-row flex-col gap-4 lg: gap-0">
      <div class="lg:w-2/3 lg:pr-3 lg:order-first order-last min-h-[calc(100vh_-_150px)] relative p-4 bg-white border border-gray-200 rounded-lg shadow-sm">
        <div id="messages" class="max-h-[calc(100vh_-_280px)] overflow-y-auto">
          <%= render partial: 'user_threads/messages/message', collection: @messages %>
        </div>
        <%= render partial: 'user_threads/messages/form', locals: { message: @message, user_thread: @user_thread, form_disabled: (@user_thread.status != 'completed') } %>
      </div>
      <div class="lg:w-1/3 lg:pl-3">
        <%= render partial: 'user_threads/topic_list', locals: { topics: @topics, current_topic_id: @user_thread.topic_id, user: current_user } %>
        <%= render partial: 'user_threads/notebook_list', locals: { notebooks: current_user.notebooks.where(topic_id: @user_thread.topic_id), user_thread: @user_thread } %>
      </div>
    </div>
  </div>
</main>